// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PuanOdulSistemi.Data;

#nullable disable

namespace PuanOdulSistemi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PuanOdulSistemi.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilFotografYolu")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Yönetici",
                            KullaniciAdi = "admin",
                            ProfilFotografYolu = (string)null,
                            Rol = "Admin",
                            Sifre = "$2a$11$CaTcykDyAFkpe9MX6Jobw.WQCfraHLCKUJrBpxex1oP6e2mPsOWYq"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Ali Yılmaz",
                            KullaniciAdi = "ali",
                            ProfilFotografYolu = (string)null,
                            Rol = "Ogrenci",
                            Sifre = "$2a$11$zZKeGD1Mk93HKqjVRMv13uXmoBL1Bw531UNgetUjNziZ8yz8K2UBe"
                        });
                });

            modelBuilder.Entity("PuanOdulSistemi.Models.Odul", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GerekliPuan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GorselYolu")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Oduller");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Renkli kalem seti",
                            Ad = "Kalem Seti",
                            GerekliPuan = 50
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Eğitici hikaye kitabı",
                            Ad = "Kitap",
                            GerekliPuan = 100
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Deney ve bilim seti",
                            Ad = "Bilim Seti",
                            GerekliPuan = 250
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Eğitim tableti",
                            Ad = "Tablet",
                            GerekliPuan = 500
                        });
                });

            modelBuilder.Entity("PuanOdulSistemi.Models.PuanBasvurusu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminNotu")
                        .HasColumnType("TEXT");

                    b.Property<string>("AktiviteAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FotografYolu")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GondermeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Puan")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("PuanBasvurulari");
                });

            modelBuilder.Entity("PuanOdulSistemi.Models.PuanBasvurusu", b =>
                {
                    b.HasOne("PuanOdulSistemi.Models.Kullanici", "Kullanici")
                        .WithMany("PuanBasvurulari")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("PuanOdulSistemi.Models.Kullanici", b =>
                {
                    b.Navigation("PuanBasvurulari");
                });
#pragma warning restore 612, 618
        }
    }
}
